config/routes.rb
Rails.application.routes.draw do
  get 'usersessions/sign_in'

  post 'usersessions/create'

  get 'usersessions/sign_out'

  resources :usersessions
  resources :posts
  resources :users

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
has_many :posts
end

app/models/usersession.rb
class Usersession < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def user_login_required
      if current_user.nil?
        flash[:notice] = "please login to view the content"
        redirect_to "/usersessions/sign_in"
    end
  end

    def current_user
      User.find_by_id(session[:user_id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :user_login_required
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :desc)
    end
    def user_login_required
      if current_user.nil?
        flash[:notice] = "please login to view the content"
        redirect_to "/usersessions/sign_in"
    end
  end

    def current_user
      User.find_by_id(session[:user_id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password)
    end
end

app/controllers/usersessions_controller.rb
class UsersessionsController < ApplicationController
  def sign_in
  	@user=User.new
  end

  def create
  	user=User.where("email = ? and password = ? ",params[:email],params[:password]).first
  	if user.present?
  		flash[:notice] = "Succesfully logged in"
  		session[:user_id]=user.id
  		redirect_to posts_path
  	else 
  		flash[:notice]  = "Invalid email or password"
  		render :action => "sign_in"
  	end
  end

  def sign_out
  	session[:user_id]=nil
  	redirect_to :action => "sign_in"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/usersessions_helper.rb
module UsersessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simpleauth</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_field :desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Desc</th>
       <th>User Id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.desc %></td>
        <td><%= post.user_id %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @post.desc %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/usersessions/_form.html.erb
<%= form_for(@usersession) do |f| %>
  <% if @usersession.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usersession.errors.count, "error") %> prohibited this usersession from being saved:</h2>

      <ul>
      <% @usersession.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sign_in %><br>
    <%= f.text_field :sign_in %>
  </div>
  <div class="field">
    <%= f.label :create %><br>
    <%= f.text_field :create %>
  </div>
  <div class="field">
    <%= f.label :sign_up %><br>
    <%= f.text_field :sign_up %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usersessions/create.html.erb
<h1>Usersessions#create</h1>
<p>Find me in app/views/usersessions/create.html.erb</p>

app/views/usersessions/edit.html.erb
<h1>Editing Usersession</h1>

<%= render 'form' %>

<%= link_to 'Show', @usersession %> |
<%= link_to 'Back', usersessions_path %>

app/views/usersessions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Usersessions</h1>

<table>
  <thead>
    <tr>
      <th>Sign in</th>
      <th>Create</th>
      <th>Sign up</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usersessions.each do |usersession| %>
      <tr>
        <td><%= usersession.sign_in %></td>
        <td><%= usersession.create %></td>
        <td><%= usersession.sign_up %></td>
        <td><%= link_to 'Show', usersession %></td>
        <td><%= link_to 'Edit', edit_usersession_path(usersession) %></td>
        <td><%= link_to 'Destroy', usersession, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usersession', new_usersession_path %>

app/views/usersessions/new.html.erb
<h1>New Usersession</h1>

<%= render 'form' %>

<%= link_to 'Back', usersessions_path %>

app/views/usersessions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sign in:</strong>
  <%= @usersession.sign_in %>
</p>

<p>
  <strong>Create:</strong>
  <%= @usersession.create %>
</p>

<p>
  <strong>Sign up:</strong>
  <%= @usersession.sign_up %>
</p>

<%= link_to 'Edit', edit_usersession_path(@usersession) %> |
<%= link_to 'Back', usersessions_path %>

app/views/usersessions/sign_in.html.erb
<%= form_tag "/usersessions/create" do %>
  <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>
  <% if flash[:error] %>
    <div class="error"><%= flash[:error] %></div>
  <% end %>

  <div class="field">
    <%= label_tag :email %><br>
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag :password %><br>
    <%= text_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag "SignIn" %>
  </div>
<% end %>

app/views/usersessions/sign_up.html.erb
<h1>Usersessions#sign_up</h1>
<p>Find me in app/views/usersessions/sign_up.html.erb</p>